# Configuracion de TLS para el reverse proxy
tls:
  certificates:
    - certFile: /etc/certs/sso.cesarsevilla.live.crt
      keyFile: /etc/certs/sso.cesarsevilla.live.key
    - certFile: /etc/certs/app.cesarsevilla.live.crt
      keyFile: /etc/certs/app.cesarsevilla.live.key

# Configuracion de HTTP para el reverse proxy
http:
  middlewares:
    keycloak-headers:
      headers:
        hostsProxyHeaders:
          - "X-Forwarded-Host"
        sslProxyHeaders:
          X-Forwarded-Proto: "https"
        customRequestHeaders:
          X-Forwarded-Proto: "https"
          X-Forwarded-Host: "sso.cesarsevilla.live"
    app-backend-headers:
      headers:
        hostsProxyHeaders:
          - "X-Forwarded-Host"
        sslProxyHeaders:
          X-Forwarded-Proto: "https"
        customRequestHeaders:
          X-Forwarded-Proto: "https"
          X-Forwarded-Host: "app.cesarsevilla.live"
    app-frontend-headers:
      headers:
        hostsProxyHeaders:
          - "X-Forwarded-Host"
        sslProxyHeaders:
          X-Forwarded-Proto: "https"
        customRequestHeaders:
          X-Forwarded-Proto: "https"
          X-Forwarded-Host: "app.cesarsevilla.live"
