tls:
  certificates:
    - certFile: /etc/certs/sso.cesarsevilla.live.crt
      keyFile: /etc/certs/sso.cesarsevilla.live.key

http:
  middlewares:
    keycloak-headers:
      headers:
        hostsProxyHeaders:
          - "X-Forwarded-Host"
        sslProxyHeaders:
          X-Forwarded-Proto: "https"
        customRequestHeaders:
          X-Forwarded-Proto: "https"
          X-Forwarded-Host: "sso.cesarsevilla.live"